version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
    environment:
      - JENKINS_JAVA_OPTIONS=-Djenkins.install.runSetupWizard=false
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarqube-db:
    image: postgres:alpine
    container_name: sonarqube-db
    networks:
      - jenkins-net
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

networks:
  jenkins-net:

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_db:
