version: '3.1'
volumes:
  sonarqube_conf: null
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_bundled-plugins: null
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - './conf.d:/etc/mysql/conf.d:ro'
  sonarqube:
    image: 'sonarqube:8.6-community'
    container_name: sonarqube
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
      - 'sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
    networks:
      - cicd
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    expose:
      - 9000
networks:
  cicd:
    driver: bridge
